export class CardView {
    renderCards(cards) {
        let wrapper = document.createElement('div');
        wrapper.classList.add('wrapper-card');
        wrapper.style.display = 'flex';
        wrapper.style.flexWrap = 'wrap';
        wrapper.style.justifyContent = 'center';
        wrapper.style.width = '100%';
        cards.forEach((card) => {
            let cardItemWrapper = document.createElement('div');
            cardItemWrapper.style.display = 'flex';
            cardItemWrapper.style.flexDirection = 'column';
            cardItemWrapper.style.alignItems = 'center';
            let nameProduct = document.createElement('p');
            nameProduct.textContent = card.title;
            let image = document.createElement('img');
            cardItemWrapper.style.width = '20%';
            image.style.width = '100%';
            image.classList.add('card-image');
            document.body.append(wrapper);
            image.src = card.images[0];
            cardItemWrapper.append(nameProduct);
            cardItemWrapper.append(image);
            wrapper.append(cardItemWrapper);
            let categoryWrapper = document.createElement('div');
            let categorySpan = document.createElement('span');
            let categorySpanValue = document.createElement('span');
            categorySpan.textContent = 'Category: ';
            categorySpanValue.textContent = card.category;
            categoryWrapper.append(categorySpan, categorySpanValue);
            cardItemWrapper.append(categoryWrapper);
            let brandWrapper = document.createElement('div');
            let brandSpan = document.createElement('span');
            let brandSpanValue = document.createElement('span');
            brandSpan.textContent = 'Brand: ';
            brandSpanValue.textContent = card.brand;
            brandWrapper.append(brandSpan, brandSpanValue);
            cardItemWrapper.append(brandWrapper);
            let priceWrapper = document.createElement('div');
            let priceSpan = document.createElement('span');
            let priceSpanValue = document.createElement('span');
            priceSpan.textContent = 'Price: ';
            priceSpanValue.textContent = card.price;
            priceWrapper.append(priceSpan, priceSpanValue);
            cardItemWrapper.append(priceWrapper);
            let ratingWrapper = document.createElement('div');
            let ratingSpan = document.createElement('span');
            let ratingSpanValue = document.createElement('span');
            ratingSpan.textContent = 'Rating: ';
            ratingSpanValue.textContent = card.rating;
            ratingWrapper.append(ratingSpan, ratingSpanValue);
            cardItemWrapper.append(ratingWrapper);
            let stockWrapper = document.createElement('div');
            let stockSpan = document.createElement('span');
            let stockSpanValue = document.createElement('span');
            stockSpan.textContent = 'Stock: ';
            stockSpanValue.textContent = card.stock;
            stockWrapper.append(stockSpan, stockSpanValue);
            cardItemWrapper.append(stockWrapper);
            let wrapperButton = document.createElement('div');
            let addBasketBtn = document.createElement('button');
            addBasketBtn.textContent = 'add to cart';
            let detailsBtn = document.createElement('button');
            detailsBtn.textContent = 'details';
            wrapperButton.append(addBasketBtn);
            wrapperButton.append(detailsBtn);
            cardItemWrapper.append(wrapperButton);
        });
    }
}
